### ISSUE TITLE
Doesn't work on macOS

### ISSUE THREAD

**Issue by rmfberlin** [NiklasPor/biblatex-snippets#1]
In a *.bib-file editiing in VSC (macOS) "@" doesn't work. There is no submenu to select @article or @book...

**Comment by NiklasPor** [comment]
Did you press auto-complete(Ctrl+Space)? 

The auto completion doesn't work without explicitly using it, due to the .bib config in VsCode (with LaTeX Workshop probably). I should definitely add this to the readme.

I am using MacOS myself so I would be quite surprised.

**Comment by rmfberlin** [comment]
OK, my fault. ctrl+space works! Sorry!
But you forgot that in the readme.md. Thanks for your work and support.

**Comment by NiklasPor** [comment]
No problem, I'll update the Readme tomorrow.
